### ISSUE TITLE
Desync in times (current game and spawning tool overlay)

### ISSUE THREAD

**Issue by marciobarroso** [StoicLoofah/spawningtool#51]
I am trying to came back to SC2 and now using again the tool.

But I don't know why the time on the game and on the overlay is aways desynchronized. Even if I try to change the parameter of speed on the tool ... I've tried on fast and faster and had the same result.

I think this could be a local machine problem, but I've found [this link](https://liquipedia.net/starcraft2/Game_Speed) and using a chronometer, I've notice that the time on the spawning tool is wrong. In faster, 60 seconds run in the same 60 seconds on my chronometer.

I will clone the repo to try fix this bug, but any way, if is already something that you guys have knowledge please let me know.

**Comment by StoicLoofah** [comment]
Yeah that's a known issue. How much is the time sync off by?

The basic reason is that most online matches have micro-lag in them, so we actually aren't precisely running at game speed, or else it woudl look like it's always running fast. So we slow it down by less than a second per minute, but maybe 5 seconds per 10 minutes (I can't remember exactly) from true game time.

Of course, it's all a guess. If you're playing versus AI where you don't need to sync against another client, then the overlay will be slow. If your ladder match is particularly laggy (again, even micro-lag that doesn't trigger the "WAITING" popup), then the overlay will be fast.

We want to use a blizzard API to sync against the actual game itself, but that unfortunately hasn't worked for us due to a specific JS error.

Did that answer your question?

**Comment by marciobarroso** [comment]
kind of ... I am playing against the AI, so this delay should no affect my game.

I've opened the game to record a video. When I am playing recording the video, there is no desync ... can you believe? Until 10 minutos, the max of 1 sec of desync. I will do some more tests and tell you the result
